# Generated by Django 5.0.6 on 2026-07-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('mailboxes', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(help_text='e.g. Re: {{original_subject}}', max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('match_type', models.CharField(choices=[('contains', 'Subject contains'), ('equals', 'Subject equals'), ('starts_with', 'Subject starts with'), ('regex', 'Subject matches regex')], default='contains', max_length=20)),
                ('match_value', models.CharField(help_text='The subject text/pattern to match', max_length=255)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower runs first; first match wins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='rules', to='attachments.attachment')),
                ('mailboxes', models.ManyToManyField(blank=True, related_name='rules', to='mailboxes.mailbox')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='rules.replytemplate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Used as {{key}} in templates', max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('static_value', models.TextField(blank=True, default='')),
                ('is_dynamic', models.BooleanField(default=False, help_text='Resolved by the engine per message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('workspace', 'key')},
            },
        ),
    ]
