# Generated by Django 5.0.6 on 2026-08-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replytemplate',
            name='is_html',
            field=models.BooleanField(default=False, help_text='Send the body as HTML'),
        ),
    ]
