# Generated by Django 5.0.6 on 2026-07-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('bot_token_encrypted', models.TextField(blank=True, default='')),
                ('chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('notify_on_sent', models.BooleanField(default=True)),
                ('notify_on_received', models.BooleanField(default=False)),
                ('notify_on_error', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_config', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Telegram configuration',
                'verbose_name_plural': 'Telegram configuration',
            },
        ),
    ]
