# Generated by Django 5.0.6 on 2026-08-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramconfig',
            name='notify_on_keyword',
            field=models.BooleanField(default=True),
        ),
    ]
