# Generated by Django 5.0.6 on 2026-08-21 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch. Off = the whole app is free and nothing is gated.')),
                ('monthly_fee_usd', models.DecimalField(decimal_places=2, default=30, max_digits=8)),
                ('period_days', models.PositiveIntegerField(default=30, help_text='How many days a confirmed payment grants.')),
                ('instructions', models.TextField(blank=True, default='', help_text='Shown to users on the payment page, e.g. how to send and what to include.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'billing settings',
                'verbose_name_plural': 'billing settings',
            },
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'USDT (TRC20)'", max_length=120)),
                ('currency', models.CharField(help_text='e.g. BTC, ETH, USDT', max_length=40)),
                ('network', models.CharField(blank=True, default='', help_text='e.g. TRC20, ERC20, Bitcoin', max_length=60)),
                ('address', models.CharField(max_length=255)),
                ('memo', models.CharField(blank=True, default='', help_text='Destination tag / memo, if the chain needs one.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(blank=True, default='', max_length=40)),
                ('tx_reference', models.CharField(blank=True, default='', help_text='Transaction hash / reference the user provides.', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.cryptowallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='billing_pay_user_id_562e66_idx')],
            },
        ),
    ]
