# Generated by Django 5.0.6 on 2026-07-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('mailboxes', '0001_initial'),
        ('rules', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('status', models.CharField(choices=[('received', 'Received'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=12)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=512)),
                ('imap_uid', models.PositiveBigIntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('thread_key', models.CharField(blank=True, db_index=True, default='', max_length=998)),
                ('from_addr', models.CharField(blank=True, default='', max_length=320)),
                ('to_addr', models.CharField(blank=True, default='', max_length=998)),
                ('body', models.TextField(blank=True, default='')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='messages', to='attachments.attachment')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailboxes.mailbox')),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='rules.rule')),
                ('reply_to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mail.emailmessage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['direction', 'status'], name='mail_emailm_directi_21db5e_idx')],
            },
        ),
    ]
