# Generated by Django 5.0.6 on 2026-08-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_emailmessage_is_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='from_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
