# Generated by Django 5.0.6 on 2026-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_emailmessage_from_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
