# Generated by Django 5.0.6 on 2026-08-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_emailmessage_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='folder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
