# Generated by Django 5.0.6 on 2026-07-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('reply_delay_minutes', models.PositiveIntegerField(default=15, help_text='Wait this long after receiving before sending an auto-reply')),
                ('poll_interval_seconds', models.PositiveIntegerField(default=30, help_text='How often the engine checks mailboxes for new mail')),
                ('signature', models.TextField(blank=True, default='', help_text='Appended to every auto-reply')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'configuration',
                'verbose_name_plural': 'configuration',
            },
        ),
    ]
