# Generated by Django 5.0.6 on 2026-08-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='poll_interval_seconds',
            field=models.PositiveIntegerField(default=10, help_text='How often the engine checks mailboxes for new mail'),
        ),
        migrations.AlterField(
            model_name='config',
            name='reply_delay_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Wait this long after receiving before sending an auto-reply'),
        ),
    ]
