# Generated by Django 5.0.6 on 2026-08-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_config_poll_interval_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='reply_once_per_thread',
            field=models.BooleanField(default=True, help_text='Only answer a given sender once per subject, per rule. Stops the same reply going out again when someone follows up on the same thread.'),
        ),
    ]
