# Generated by Django 5.0.6 on 2026-08-28 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_userprofile_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('password_encrypted', models.TextField(blank=True, default='')),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('scan_inbox', models.BooleanField(default=True)),
                ('scan_sent', models.BooleanField(default=True)),
                ('scan_spam', models.BooleanField(default=False)),
                ('extra_folders', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('folder_cursors', models.JSONField(blank=True, default=dict)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_mailboxes', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'watched mailbox',
                'verbose_name_plural': 'watched mailboxes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('keywords', models.TextField(help_text='Comma or newline separated.')),
                ('match_subject', models.BooleanField(default=True)),
                ('match_body', models.BooleanField(default=True)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('watch_incoming', models.BooleanField(default=True)),
                ('watch_outgoing', models.BooleanField(default=True)),
                ('notify_telegram', models.BooleanField(default=True)),
                ('max_alerts_per_hour', models.PositiveIntegerField(default=20)),
                ('suppressed_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='workspaces.workspace')),
                ('mailboxes', models.ManyToManyField(blank=True, related_name='watches', to='checks.watchmailbox')),
            ],
            options={
                'verbose_name_plural': 'watches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WatchHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('keyword', models.CharField(max_length=200)),
                ('matched_in', models.CharField(blank=True, default='', max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('from_addr', models.CharField(blank=True, default='', max_length=320)),
                ('to_addr', models.CharField(blank=True, default='', max_length=998)),
                ('folder', models.CharField(blank=True, default='', max_length=255)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('notified', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='checks.watch')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_hits', to='workspaces.workspace')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='checks.watchmailbox')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='checks_watc_workspa_ef1b57_idx'), models.Index(fields=['watch', 'message_id'], name='checks_watc_watch_i_514771_idx')],
            },
        ),
    ]
