# Generated by Django 5.0.6 on 2026-08-21 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0002_mailbox_use_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='poll_interval_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='How often to check this account. Blank = workspace default.', null=True, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='reply_delay_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Wait this long before auto-replying from this account. Blank = workspace default.', null=True),
        ),
    ]
