# Generated by Django 5.0.6 on 2026-08-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0003_mailbox_poll_interval_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='extra_folders',
            field=models.CharField(blank=True, default='', help_text="Extra IMAP folders to scan, comma-separated (e.g. 'Promotions, Archive').", max_length=500),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='folder_cursors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='scan_spam',
            field=models.BooleanField(default=True, help_text="Also scan this account's Spam/Junk folder for incoming mail."),
        ),
    ]
